_wandb:
    value:
        cli_version: 0.23.0
        e:
            qwwplrq03qdx2j1pjhd6204c0a8i6ogc:
                args:
                    - --lr
                    - "3e-5"
                    - --epochs
                    - "3"
                    - --batch_size
                    - "32"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999306555392"
                        used: "603213422592"
                email: mateuszmakola4@gmail.com
                executable: C:\Users\mateu\AppData\Local\Programs\Python\Python311\python.exe
                gpu: NVIDIA GeForce RTX 2080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2944
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080
                      uuid: GPU-9389880f-2a27-a06f-528f-f9cfcb1ae96b
                host: pidzudle
                memory:
                    total: "17097371648"
                os: Windows-10-10.0.26100-SP0
                program: C:\MLOPS\main.py
                python: CPython 3.11.8
                root: C:\MLOPS
                startedAt: "2025-11-12T19:01:38.456071Z"
                writerId: qwwplrq03qdx2j1pjhd6204c0a8i6ogc
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.11.8
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 32
checkpoint_dir:
    value: models/
epochs:
    value: 3
lr:
    value: 3e-05
seed:
    value: 42
wandb_project:
    value: my-project
